### HTTP Client Requests for node-ts-express-api
@host = localhost
@port = 3000
@protocol = http

@url = {{protocol}}://{{host}}:{{port}}

#### Get Root Endpoint
GET {{url}}/
```
#### Post New User
POST {{url}}/user
Accept: application/json
Content-Type: application/json

{
  "name": {
    "first": "John",
    "last": "Doe" 
  }
}