### HTTP Client Requests for node-ts-express-api

@host = localhost
@port = 3000
@protocol = http

@url = {{protocol}}://{{host}}:{{port}}

#### Get Root Endpoint
GET {{url}}/
```
#### Post Example (if applicable in the future)
POST {{url}}/user?param1=value1&param2=value2
Accept: application/json
Content-Type: application/json

{
  "name": {
    "first": "John",
    "last": "Doe" 
  }
}